version: '3.8'

services:
  mongodb:
    image: mongo:latest
    container_name: dsa_mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db

  leetcode-api:
    image: alfaarghya/alfa-leetcode-api:2.0.3
    container_name: dsa_leetcode_api
    ports:
      - "3002:3000"
    restart: unless-stopped

volumes:
  mongodb_data:
